repos:
  - repo: local
    hooks:
      - id: cs-hook
        name: csProjectManager/hooks/cs-hooks
        language: script
        entry: ../csProjectManager/hooks/run-cs-hooks
        verbose: true
